#!/bin/bash

BUILD_DIR=$HOME/build
BUILDROOT_DIR=$BUILD_DIR/buildroot
SCRIPT_PATH=$(
  cd "$(dirname "$0")"
  pwd
)
CONFIG_FILE_NAME=.config
SRC_CONFIG_FILE=$SCRIPT_PATH/$CONFIG_FILE_NAME
DST_CONFIG_FILE=$BUILDROOT_DIR/$CONFIG_FILE_NAME
BUILD_IMAGES_DIR=$BUILDROOT_DIR/output/images
SAVE_IMAGES_DIR=$SCRIPT_PATH/images

cd $BUILDROOT_DIR
make clean
cp $SRC_CONFIG_FILE $DST_CONFIG_FILE
make
mkdir -p $SAVE_IMAGES_DIR
cp $BUILD_IMAGES_DIR/* $SAVE_IMAGES_DIR
